#!/usr/bin/env python3
"""Generate tests/data/morton_boundary_golden.json (issue #8 golden boundary vectors).

The fixture pins the latitude convention of the published morton stores:
**authalic-WGS84** (espg/mortie#186 made geodetic->authalic ingress the mortie
default, and englacial/zagg#549 confirmed the shipped source-coop stores were
written under it — the ruling on espg/gridlook#8 supersedes that issue body's
older plain-sphere note). mortie's boundary egress applies the inverse series,
so every vertex below is geodetic WGS84 lat/lon; the browser reproduces them
with healpix-geo's ellipsoidal (authalic) mode. Rendering the same cells in
plain sphere mode instead mis-places boundaries by ~0.1283 deg (~14.26 km)
near 45 deg latitude — the fixture carries that expectation as the negative
control.

Requires mortie >= 1.0 **installed with its test data**: the geodetic<->authalic
parity pairs are copied from mortie's committed reference vectors
(mortie/tests/data/authalic_reference.json, mpmath 60 dps), which a plain
`pip install mortie` wheel need not ship. See load_authalic_reference().

Usage: python scripts/generate_morton_boundary_golden.py
"""

import json
import os
import sys

import mortie
import numpy as np

OUT = os.path.join(os.path.dirname(__file__), "..", "tests", "data", "morton_boundary_golden.json")

#: (label, lat, lon, order) — orders 0/9/14/24 cover a base cell in each
#: hemisphere, the shipped o9 store order at the ~45 deg latitude where the
#: sphere-vs-authalic error is maximal, a deeper cell, and the deepest
#: float64-exact order (24, mortie spec section 4 viewer cast bound).
CELLS = [
    ("north_base", 45.0, 12.0, 0),
    ("south_base", -75.0, 200.0, 0),
    ("midlat_o9", 45.0, 12.0, 9),
    ("south_midlat_o9", -45.0, 200.0, 9),
    ("midlat_o14", 45.0, 12.0, 14),
    ("midlat_o24", 45.0, 12.0, 24),
]


def cell_entry(label: str, lat: float, lon: float, order: int) -> dict:
    # `latitude=` is named at both mortie call sites on purpose: it is the very
    # convention this fixture exists to pin, and mortie's default flipped once
    # already (espg/mortie#186 made "authalic" the default; "geodetic-spherical"
    # is the superseded value). A future default flip must break this script
    # loudly rather than silently rewrite the golden under the other convention.
    word = int(
        np.asarray(
            mortie.geo2mort(
                np.array([lat]), np.array([lon]), order=order, latitude="authalic"
            ),
            dtype=np.uint64,
        )[0]
    )
    nested, got_order = mortie.mort2healpix(word)
    assert int(got_order) == order, (label, got_order, order)
    # closed ring, [lat, lon], geodetic WGS84
    ring = mortie.mort2polygon(word, step=1, latitude="authalic")
    corners = ring[:-1]
    assert len(corners) == 4, (label, len(corners))
    return {
        "label": label,
        "word": str(word),
        "order": order,
        "nested": str(int(np.asarray(nested).ravel()[0])),
        "corners_lat_lon": corners,
    }


def load_authalic_reference() -> dict:
    """mortie's committed geodetic<->authalic reference vectors (mpmath, 60 dps).

    This lives in mortie's *test* tree, which is not part of its public API and
    is not covered by its version contract: a wheel built without the test data
    simply will not have it. Fail with an actionable message rather than a bare
    FileNotFoundError on a long path.
    """
    ref = os.path.join(os.path.dirname(mortie.__file__), "tests", "data", "authalic_reference.json")
    if not os.path.exists(ref):
        sys.exit(
            f"mortie reference vectors not found at {ref}\n"
            "This script needs a mortie install that ships mortie/tests/data/ (a source "
            "checkout, or a wheel built with the test data) — the vectors are mortie's "
            "mpmath 60 dps reference, generated by its tests/generate_authalic_reference.py. "
            "Install mortie from source and re-run."
        )
    with open(ref) as f:
        payload = json.load(f)
    return payload


def reference_pairs(payload: dict, key: str) -> list[list[float]]:
    """Degree pairs from one direction of mortie's reference table.

    `forward_deg` rows are [geodetic, authalic] sampled at round geodetic
    latitudes; `inverse_deg` rows are [authalic, geodetic] sampled at round
    authalic ones, so the two are independent sample sets, not a transpose.

    The reference rows are decimal *strings* carrying more digits than float64
    (e.g. ['-89', '-88.99551395786199602910539']); float() truncating them to
    the nearest double is deliberate — float64 is the precision the browser
    compares at.
    """
    return [[float(first), float(second)] for first, second in payload[key]]


def sphere_deviation_deg(cell: dict) -> float:
    """Corner mis-placement, in degrees, if the cell is rendered on a plain sphere.

    Sphere mode hands back the raw spherical (= authalic) vertex latitudes, while
    mortie's egress converts them to geodetic, so the gap at each corner is just
    geodetic - authalic at that latitude. Derived per control cell, not a
    remembered constant: it is ~0.1283 deg at order 9 but ~0.1275 deg at order 0,
    because the corner latitudes differ.
    """
    lats = np.array([corner[0] for corner in cell["corners_lat_lon"]], dtype=np.float64)
    return float(np.max(np.abs(lats - mortie.geodetic_to_authalic(lats))))


def main() -> None:
    payload = load_authalic_reference()
    cells = [cell_entry(*spec) for spec in CELLS]
    control_label = "midlat_o9"
    control = next(cell for cell in cells if cell["label"] == control_label)
    fixture = {
        "comment": (
            "Golden boundary vectors for the morton->healpix-geo path (espg/gridlook#8). "
            "Generated by scripts/generate_morton_boundary_golden.py with mortie "
            f"{mortie.__version__}; corners are geodetic WGS84 [lat, lon] from "
            "mort2polygon under the authalic-WGS84 store convention "
            "(espg/mortie#186, englacial/zagg#549)."
        ),
        "convention": "authalic-wgs84",
        # Derived from mortie's own reference block, so a mortie ellipsoid change
        # cannot leave the fixture asserting a stale body.
        "wgs84": {
            "semi_major_axis": float(payload["wgs84"]["a"]),
            "inverse_flattening": float(payload["wgs84"]["inv_f"]),
        },
        "cells": cells,
        "negative_control": {
            "cell": control_label,
            "min_sphere_deviation_deg": 0.1,
            "expected_sphere_deviation_deg": sphere_deviation_deg(control),
        },
        # Ingress: [geodetic, authalic]. Egress (what the boundary path runs):
        # [authalic, geodetic].
        "authalic_pairs_deg": reference_pairs(payload, "forward_deg"),
        "geodetic_pairs_deg": reference_pairs(payload, "inverse_deg"),
    }
    with open(os.path.abspath(OUT), "w") as f:
        json.dump(fixture, f, indent=1)
        f.write("\n")
    print(f"wrote {os.path.abspath(OUT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
